name: Proto

on:
  pull_request:
    paths:
      - .github/workflows/proto.yml
      - bin/protoc*
      - '**/*.proto'
      - '**/gen/**/*.go'

permissions:
  contents: read

jobs:
  proto-diff:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    container: ghcr.io/linkerd/dev:v39-go
    steps:
      - run: apt update && apt install -y unzip
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - run: bin/protoc-diff

